### ISSUE TITLE
Start multiple processes as children of a single j4-dmenu-desktop 

### ISSUE THREAD

**Issue by hyiltiz** [enkore/j4-dmenu-desktop#107]
When I open multiple apps with `j4-demnu-desktop`, each call creates a new process for it as well as the apps. Opening `htop` with the tree view shows a lot of them; it would be much better if only one `j4-demnu-desktop` is running and calls them all, which is what happens if I open those apps directly from within bash with `&`.

**Comment by enkore** [comment]
How do you invoke it exactly? By default the select app will be exec'd without creating a new process (the new process replaces the j4dd process).

**Comment by hyiltiz** [comment]
I have this single line mentioning it in my i3 config:
```
# rg j4 ~/.config/i3/config
76:bindsym $mod+d exec --no-startup-id j4-dmenu-desktop
```

I then press `command+d` then type `leafpad` and press Enter. Then press `command+d`, type `kate` and press Enter and so forth. This is what I get in htop:
![image](https://user-images.githubusercontent.com/3246683/96374881-8cf0bb80-1143-11eb-9c0d-c5920a9cec2f.png)

**Comment by enkore** [comment]
Ah you see, that's not up to j4dd ;)

You're seeing the *shell* process started by i3, which in turn is ordered to start j4dd, which replaced itself properly with the command you selected.

You could use the daemon mode but there's really not that much point unless you're having a slowness issue due to e.g. spinning hard drive and little RAM.

**Comment by hyiltiz** [comment]
Hmm I might want to try out the daemon mode then; it doesn't seem to be documented in its man page, this repo front page, nor the wiki or the issues. How do I enable and use it?

**Comment by enkore** [comment]
It's not a real daemon more like something waiting in the dark

```
--wait-on=<path>
    Must point to a path where a file can be created.
    In this mode no menu will be shown. Instead the program waits for <path>
    to be written to (use echo > path). Every time this happens a menu will be shown.
    Desktop files are parsed ahead of time.
    Perfoming 'echo -n q > path' will exit the program.
```

**Comment by hyiltiz** [comment]
Hmm, so for `i3wm`, we can use the following config?
```
# bindsym $mod+d exec --no-startup-id j4-dmenu-desktop
exec --no-startup-id j4-dmenu-desktop --wait-on=/var/$USER/j4dd.socket
bindsym $mod+d exec --no-startup-id echo > /var/$USER/j4dd.socket
```

`--wait-on` doesn't seem to bne supported in `2.16-1+b1`. From git-blame it seems it was introduced 2 years ago; so sad newer versions never got packaged to Debian (testing).
