### ISSUE TITLE
zsh: bad pattern error on app open

### ISSUE THREAD

**Issue by lyiriyah** [enkore/j4-dmenu-desktop#108]
Whenever I run any program through j4 i get:
`zsh:1: bad pattern: ^[[H^[[2J^[[3J` and the first word of the application opened (e.g ^[[H^[[2J^[[3JFirefox for Firefox Developer Edition)

I am using dwm-6.2 on Manjaro with Linux 5.8.16-2, I built from source.

**Comment by enkore** [comment]
Do you maybe have a `clear` or something like that in the shell startup files?

**Comment by lyiriyah** [comment]
don't worry, i found an alternative
