### ISSUE TITLE
Support for custom aliases

### ISSUE THREAD

**Issue by orschiro** [enkore/j4-dmenu-desktop#11]
Hi there, 

Thanks a lot for j4-dmenu-desktop! Whilst having support for `.desktop` files is great, not every single command is worth a desktop file. Thus it would be even better if custom user aliases, such as provided by a `~/.bash_aliases` or `~/.zsh_aliases`, could be supported alike.

What do you think?

Bests, 

Robert

**Comment by varac** [comment]
Btw, I solved this by adding `grep '^alias' .sh_aliases | 
tr '=' ' ' | cut -f2 -d' '; ` to the application list piped to bemenu:

```
set $menu SHELL=/bin/sh j4-dmenu-desktop --dmenu="(grep '^alias' .sh_aliases | 
tr '=' ' ' | cut -f2 -d' '; (stest -flx $(echo $PATH | tr : ' ') | sort -u)) | bemenu -n -i --nb '#3f3f3f' --nf '#dcdccc' --sf '#f9e907' --fn 'pango:DejaVu Sans Mono 12'" | xargs swaymsg exec --                                                                                                                                           
bindsym $mod+d exec $menu
```
