### ISSUE TITLE
Debian testing (bullseye)

### ISSUE THREAD

**Issue by ana-borges** [enkore/j4-dmenu-desktop#113]
Could you add this to the Debian testing (bullseye as of now) repository please?

**Comment by enkore** [comment]
I believe you need to raise this with Debian using a request-for-package: https://wiki.debian.org/RFP

**Comment by ana-borges** [comment]
After looking more into this, it seems that j4-demenu-desktop will be included in Debian testing when there are no pending bugs. However there is one right now: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972992 (see also https://packages.qa.debian.org/j/j4-dmenu-desktop.html).

The bug is just a missing dependency, so in the meantime I've compiled from source :)
