### ISSUE TITLE
Passing --dmenu removes .desktop applications from results

### ISSUE THREAD

**Issue by fnune** [enkore/j4-dmenu-desktop#121]
Hey - thanks a lot for your application.

I've run into a silly problem: running `j4-dmenu-desktop` on its own produces the correct set of programs, scanning my `$XDG_DATA_DIRS` and others. However, passing a custom `--dmenu` option, I can no longer access the .desktop entries.

I've read the man page and the `README` but I can't figure out how to keep all the entries even if passing `--dmenu`.

My command:

`j4-dmenu-desktop --dmenu='dmenu_run -l 8'`

Thanks a lot in advance, and sorry about the basic question.

**Comment by enkore** [comment]
--dmenu is for specifying an alternate dmenu(1) implementation or
parameters for that, but dmenu_run is another menu (also using dmenu
under the hood). It can't be used in this context.

**Comment by fnune** [comment]
Oh god, silly mistake. Thank you so much!

For others:

```diff
- j4-dmenu-desktop --dmenu='dmenu_run -i -l 8 -fn "Cascadia Code:12"'
+ j4-dmenu-desktop --dmenu='dmenu -i -l 8 -fn "Cascadia Code:12"'
```
