### ISSUE TITLE
Options to configure font and colors

### ISSUE THREAD

**Issue by danijar** [enkore/j4-dmenu-desktop#127]
I would like to switch from dmenu to j4-dmenu-desktop. However, it seems like the latter does not support setting the font and colors. As a result, it is barely visible on my hi-res screen and does not fit in with the color scheme of my window manager. I'm currently using the following command:

```
dmenu_run \
    -fn 'DejaVu Sans Mono:pixelsize=19' \
    -nb '#3a3a3a' -nf '#adada2' -sb '7f9f7f' -sf '3a3a3a'
```

Is there a way to configure font (including font size) and colors for j4-dmenu-desktop? If not, would it be possible to add this functionality? The tool would likely see more adoption if it were to function as a (faster) drop-in replacement of dmenu.

**Comment by meator** [comment]
J4-dmenu-desktop isn't a replacement of dmenu. It actually uses dmenu under the hood. This means that you can do the same thing you did with `dmenu_run`:
```shell
j4-dmenu-desktop --dmenu "dmenu -fn 'DejaVu Sans Mono:pixelsize=19' -nb '#3a3a3a' -nf '#adada2' -sb '#7f9f7f' -sf '#3a3a3a'"
```

**Comment by enkore** [comment]
What @meator says :)

**Comment by danijar** [comment]
Awesome!
