### ISSUE TITLE
Can you change the font size?

### ISSUE THREAD

**Issue by root2185** [enkore/j4-dmenu-desktop#133]
I also use dmenu and I'd like to have both the same size.

**Comment by meator** [comment]
j4-dmenu-desktop uses dmenu internally, so if your dmenu uses your desired fontsize by default, j4-dmenu-desktop will too. If you want to override dmenu defaults, you can do:
```sh
j4-dmenu-desktop --dmenu "dmenu -fn <font description>"
```

The `<font description>` can be any font name accepted by fontconfig (i.e. the thing you put [here](https://git.suckless.org/dmenu/file/config.def.h.html#l7)). You can find more info on how to specify font name in https://www.freedesktop.org/software/fontconfig/fontconfig-user.html (specifically in sections _Font Names_ and _Font Properties_). You should also read https://wiki.archlinux.org/title/Font_configuration.

**Comment by root2185** [comment]
I changed dwm top bar not dmenu, right.

**Comment by root2185** [comment]
I can change `dmenu` font with: `dmenu_run -fn "FuraMono Nerd Font:size=11.5"`.

But it doesn't work for `j4-dmenu-desktop`.
It is always the same, e.g. with `j4-dmenu-desktop --dmenu "dmenu -fn "FuraMono Nerd Font:size=46""`.

**Comment by meator** [comment]
This isn't a problem with j4-dmenu-desktop. Your command is incorrectly quoted. When you have text enclosed in quotation marks which is also enclosed in quotation marks, you have to distinguish the inner and outer `"`s.

Your quoted string are this
```
"dmenu -fn "
```
and this
```
""
```
which presumably isn't what You intended.

You can use
```sh
j4-dmenu-desktop --dmenu 'dmenu -fn "FuraMono Nerd Font:size=46"'
```
or
```sh
j4-dmenu-desktop --dmenu "dmenu -fn \"FuraMono Nerd Font:size=46\""
```
to distinguish the quotation marks. There are many ways to do this, look up your shell's documentation for more information (this technique is called shell quoting).
