### ISSUE TITLE
Sorting by display name case insensitively

### ISSUE THREAD

**Issue by nabakolu** [enkore/j4-dmenu-desktop#136]
When launching, the display names for the apps are sorted case sensitively like this:
```
AAA
BBB
CCC
aaa
bbb
ccc
```
Is there a way to make j4-dmenu-desktop sort case insensitively? Like this:
```
AAA
aaa
BBB
bbb
CCC
ccc
```

**Comment by meator** [comment]
I don't think this is possible out of the box. But j4dd executes dmenu with the `-i` flag by default so the actual selection of desktop entry will be done case insensitively.

If you want to, I can provide You a patch that would add this functionality (You'll have to compile j4dd to apply it) and/or I could make a pull request.

**Comment by nabakolu** [comment]
Ok im gonna write a patch then.

**Comment by enkore** [comment]
Fixed by #137
