### ISSUE TITLE
XDG_DESKTOP_DIR in user-dirs.dir not being read

### ISSUE THREAD

**Issue by wqvi** [enkore/j4-dmenu-desktop#182]
I'm not sure if this falls within the scope of the project, but I believe it to be an issue. j4-dmenu-desktop is not reading the XDG_DESKTOP_DIR variable from user-dirs.dir. As XDG_DESKTOP_DIR is a directory that can contain shortcuts, it would be beneficial to read from there, as this could be useful to other users.
I believe the relevant files that may need editing include SearchPath.cc, Utilities.hh, and Utilities.cc. Additionally, we would be unable to use the xdg-user-dirs project due to it being licensed under GPLv2, while this project is GPLv3.
_Edit: I've started working on this and will submit a pull request soon. Looking forward to any feedback or suggestions!_

**Comment by meator** [comment]
Thanks for reporting this!

Shortcuts used in the localized `Desktop` directory can often point to files or directories (I believe that this is the main purpose of shortcuts). These shortcuts shouldn't be handled by j4-dmenu-desktop (an application launcher), this task is more appropriate for file explorers and "desktop" handlers of desktop managers.

Are you talking about application shortcuts? I personally don't use a desktop environment (I don't have a "desktop"), so please explain your use-case in more detail. Are there any applications that are linked in the `XDG_DESKTOP_DIR` directory but aren't present in standard desktop file directories? I don't think that happens very often.

**Comment by wqvi** [comment]
Thanks for your quick response!

Based on your explanation, it sounds like what I am trying to achieve might indeed not be necessary. Specifically I was looking to launch shortcuts created by Prismlauncher.

I understand that j4-dmenu-desktop is primarily for launching applications, and handling desktop shortcuts is more suitable for file explorers or desktop managers. My use-case involves application shortcuts placed in the XDG_DESKTOP_DIR directory by Prismlauncher, which might not always align with standard desktop file directories. Since I am also not using a traditional desktop environment (I am using DWL), I'm trying to find an alternative way to launch these shortcuts.

Thanks for considering this, and I appreciate your help!

**Comment by wqvi** [comment]
Hi meator,
Just checking in to see if there are any thoughts on the issue I raised a couple days ago. If there's interest, I'm happy to open a pull request with the proposed changes.
Thanks!

**Comment by meator** [comment]
A workaround would be to copy/move the relevant desktop files from `~/Desktop` to `~/.local/share/applications`.

Do any other desktop file launchers do what you propose? You have already done some research in #183, so I'd be interested about what others do.

This feature is very unlikely to be merged. I will investigate how Prism Launcher handled desktop files and then likely close this issue as not planned.

**Comment by wqvi** [comment]
[#183](https://github.com/enkore/j4-dmenu-desktop/pull/183)'s research was exclusively on fixing mixed single and double quote Exec paths from Prism Launcher (and won't be supported). Unfortunately no other launcher does what I propose. I appreciate your time thank you!
