### ISSUE TITLE
Search by GenericName

### ISSUE THREAD

**Issue by lewtds** [enkore/j4-dmenu-desktop#31]
The program should consider an app's description when doing the search. For example, I always search for "vector" instead of "Inkscape" because I (and I think most people as well) have poor memory and cannot remember an app's specific name but only what it does.

**Comment by Zopieux** [comment]
I think this is a good idea. PR #33 implements that. If it gets merged, this issue can be closed.

**Comment by msx** [comment]
Hi all,
Another good example is The GIMP: in Fedora I have it listed as GNU Image blah/blah, I would like to search for 'gimp' as I'm used to with vanilla dmenu.

Btw, I love j4 so far.
