### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by cinemast** [enkore/j4-dmenu-desktop#35]
Hi!

j4-dmenu-desktop is a great tool. I would like to package it for debian. However there are some things that I would need you to change before I can package it into debian:

["please" implied for all of the following]

- sign your releases using gpg (described here: LibVNC/libvncserver#65)
- add a manpage (I can help you with that)

Even if you make all these changes, I cannot promise you that it will end up in debian soon, but I will do my best to get an upload.

Please let me know what you think of this... and again, great project :+1:

**Comment by enkore** [comment]
Would it suffice to sign the release tag(s)?

**Comment by cinemast** [comment]
No. Please sign the .tar.gz tarballs.

**Comment by enkore** [comment]
I created a signature for the tarball (at least, I *think* I did that\*) ; let's hope GitHubs .tar.gz creation is deterministic...

\* for future reference so I don't forget how this is done:

1. Fetch .tar.gz from GH
1. Extract
1. diff extracted tarball and local repo
1. gpg --output rxxxx.tar.gz.sig --detach-sign rxxxxx.tar.gz with key 9B8450B91D1362C1
1. Upload .sig to GH

**Comment by Zopieux** [comment]
Please be aware that Github fails at creating tarballs for *big* projects. I've seen it fail for Raspberry Linux kernel (300MB). I won't rely on that anymore, even for smaller projects. But I guess it is safe for a few-kb project like `j4-demu-desktop`.

**Comment by cinemast** [comment]
For my projects it is working pretty fine. And a lot of projects use it. So maybe for big tarballs it is not working. But I guess that is not an issue for this project.

**Comment by cinemast** [comment]
Can you make a sense of why this testcase is failing?

```sh
1/1 Test #1: j4-dmenu-tests ...................***Failed    0.00 sec
/tmp/buildd/j4-dmenu-desktop-2.12/obj-x86_64-linux-gnu/some-file-that-doesnt-exist: No such file or directory
1234 --caption "Regression Test 18"

j4-dmenu-tests is a Catch v1.0 b10 host application.
Run with -? for options


SearchPath/XDG_DATA_HOME

/tmp/buildd/j4-dmenu-desktop-2.12/src/TestSearchPath.cc:12


/tmp/buildd/j4-dmenu-desktop-2.12/src/TestSearchPath.cc:20: FAILED:
  REQUIRE( result.size() == 1 )
with expansion:
  0 == 1

===============================================================================
19 test cases - 1 failed (53 assertions - 1 failed)
```

**Comment by enkore** [comment]
Works for me... also http://golem.enkore.de/job/j4-dmenu-desktop-dev/20/console

**Comment by cinemast** [comment]
Hm.. strange. Is there maybe an undocumented dependency, like having an X-Server installed and running or something like that?

**Comment by cinemast** [comment]
I think it fails when there is no /usr/share/applications folder on the system.

**Comment by justin8** [comment]
That folder should be created by one of your base system packages. I'm not too familiar with the Debian packaging standards but arch/fedora/rhel all have that with a basic desktop environment. You might have to depend on whatever provides it for the deb.

**Comment by cinemast** [comment]
I patched out this specific testcase. The package got uploaded into Debian. Now it is up to the ftp-masters when it will be in official repos.

https://ftp-master.debian.org/new/j4-dmenu-desktop_2.12-1.html

Thank you for your support.

**Comment by cinemast** [comment]
Your software officially arrived at debian :)

https://packages.debian.org/sid/j4-dmenu-desktop
