### ISSUE TITLE
[REQ] Enable antialias

### ISSUE THREAD

**Issue by LeonardKoenig** [enkore/j4-dmenu-desktop#36]
This would be a nice improvement if it would respect fonts.conf.

Is that possible for you?

Thanks

Maybe this could be used as a reference?
http://lists.suckless.org/dev/att-2320/dmenu-4.0-xft2.diff

**Comment by enkore** [comment]
We're just invoking dmenu, so this isn't a dmenu implementation. You can use any dmenu you like, including any with xft patches and so on. See --dmenu option

**Comment by LeonardKoenig** [comment]
oh, ok. Thanks for the info :-)
