### ISSUE TITLE
Print to standard output instead of passing to dmenu

### ISSUE THREAD

**Issue by roomcays** [enkore/j4-dmenu-desktop#39]
I wonder if it is possible to print everything that `j4-dmenu-desktop` passes to dmenu to standard output.
I am trying to integrate `j4-dmenu-desktop` with [rofi](https://davedavenport.github.io/rofi/) so it can be used as one of it's so-called "modis" instead of be executed via `j4-dmenu-desktop`'s `--dmenu` argument.

The best I've come so far is using temporary file, as simple `cat` does not work (tries to execute first element, interpreting new line character as a user interaction):

    j4-dmenu-desktop --dmenu="cat > /tmp/elements.txt" 2>&1 1>/dev/null

This, however, is just a half way to the success, because:
1. uses temporary file
2. loses relation between element name and `.desktop` file it is related with; this is how temporary file looks like:

    Atom Zombie Smasher
    Bastion
    Cogs
    Legend of Grimrock
    Half-Life 2 (Beta)
    Portal (Beta)

How this could be accomplished, if at all?

**Comment by anschch** [comment]
I just ran into the same "problem" and trying to figure it out. I've also been looking for alternatives to j4-dmenu-desktop that could print available programs from .desktop to standard output, but to no avail so far.

**Comment by enkore** [comment]
There is a command line utility to introspect .desktop files written in Python by an Arch Linux guy, hosted in Github. Don't know the name, though, but you may be able to find it.

**Comment by enkore** [comment]
While I took a stab at #51, I remembered this.

This should work, mostly:

    #!/bin/sh
    CURPID=$$
    STDOUT=$(readlink -f /proc/$CURPID/fd/1)
    j4-dmenu-desktop --dmenu="tee $STDOUT 1>&2 ; cat << EOF"

It relies on some conventions, i.e. readlink -f resolving symlinks, /proc/$PID, and that FD 1 of a shell process is the active standard output. You'll need to put this in a script and run that.

**Comment by roomcays** [comment]
Wow, I have not expected this :+1: 
I have tried your script and it nicely prints out list of application names to the console, but when combined with [rofi](https://davedavenport.github.io/rofi/) it - strangely - does not work :(
Something is telling me that it might be the case of output redirection, but I am not able to prove it...

**Comment by enkore** [comment]
Hm, this should be transparent if the shell script is run like a shell script in a separate shell process. I don't know Rofi, maybe it documents somewhere how exactly it implements these modis.

**Comment by roomcays** [comment]
I will report this *issue* to Rofi's developer, he might be interested.
