### ISSUE TITLE
Is it possible to change the font?

### ISSUE THREAD

**Issue by adsch** [enkore/j4-dmenu-desktop#41]
Because it is very small and hard to read. I know the regular dmenu can use xftfonts.

**Comment by enkore** [comment]
#38 #34 #10

**Comment by parthsharma1996** [comment]
@enkore  I tried passing the arguments using the --dmenu option but it doesn't seem to work. 
This is the corresponding line from my i3 config
`bindsym $mod+d exec j4-dmenu-desktop --dmenu=dmenu_run -fn "-xos4-terminus-medium-r-*-*-14-*"`

**Comment by enkore** [comment]
Needs more quotes. Try

```
bindsym $mod+d exec j4-dmenu-desktop --dmenu='dmenu_run -fn "-xos4-terminus-medium-r-*-*-14-*"'
```

**Comment by parthsharma1996** [comment]
> Needs more quotes. Try
> 
> ```
> bindsym $mod+d exec j4-dmenu-desktop --dmenu='dmenu_run -fn "-xos4-terminus-medium-r-*-*-14-*"'
> ```

Works like a charm. Thanks!
