### ISSUE TITLE
Sort entries by usage frequency

### ISSUE THREAD

**Issue by ghost** [enkore/j4-dmenu-desktop#46]
Would it be possible to put entries that are more frequently used in the front?

For example you have 2 entries "File Manager" and "Firefox". Alphabetically "File Manager" should come before "Firefox". But if I launch "Firefox" more often it would be nice to take that into account. Meaning that it should prefer entries that are used more frequently.

**Comment by bhcopeland** [comment]
+1

**Comment by adrian17** [comment]
I'd prefer if this was opt-in, as I don't imagine using it myself. If I use the application often, it's muscle memory to quickly press 3-4 first letters of its name. Here, frequency can change at any time and you can't rely on X always being on, say 3rd position, you have to visually check it. And if I use the application *very* often, I have it bound to a shortcut.

**Comment by enkore** [comment]
Check out the `usage-freq` branch. It should be very low profile for users who don't want it.

New option for this: --usage-log=<file>

<file> must be R/W. We'll store a list of used apps in there and how often they have been used. Then we sort the applications (stable) after sorting them alphabetically. So your most used apps come first, equally often used apps sorted alphabetically.

**Comment by enkore** [comment]
Merged into `master`

**Comment by bhcopeland** [comment]
thank you will test it out!
