### ISSUE TITLE
I updated my system (archlinux) and now j4-dmenu-desktop is using the wrong font. I belive it was set to the default i3 font but now it appears to be Noto Sans Mono. How can I fix this?

### ISSUE THREAD

**Issue by t3zla** [enkore/j4-dmenu-desktop#49]
The font I am using in i3 is

    -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1

**Comment by t3zla** [comment]
I tried some stuff and it appears I can only use one generic font in i3 if I use pango, and I am not sure what that font is

**Comment by t3zla** [comment]
dmenu_run -fn "-misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1"

does not work either

**Comment by enkore** [comment]
dmenu does only support X11 fonts by itself, maybe you overwrote your dmenu with Xft patches with the stock dmenu?

**Comment by t3zla** [comment]
That was the problem, I overwrote it. Thanks man!
