### ISSUE TITLE
Show executables also

### ISSUE THREAD

**Issue by mirkojovanovic** [enkore/j4-dmenu-desktop#51]
I want to have desktop files first and executables after. Is this possible?

**Comment by enkore** [comment]
Nothing a little sh can't fix

    j4-dmenu-desktop --dmenu="((cat ; (stest -flx $(echo $PATH | tr : ' ') | sort -u)) | dmenu)"

**Comment by mirkojovanovic** [comment]
What if I have some dmenu options like colors? I just pasted your code and pipeline in front of dmenu command with arguments that worked before but it won't run as it should.

**Comment by mirkojovanovic** [comment]
Sorry, it's ok, but when I assign it to a key in i3 config file I get error.

**Comment by enkore** [comment]
It might be an escaping issue. Last time I had those I just created a shell script containing the "complicated" shell code, so in my config I just have something like

    bindsym $mod+space desktop_menu.sh

That's way easier than to figure out the *n* levels of quoting and escaping. I created myself a `~/.local/bin` for things like these, so I don't even have to type the explicit path to this kind of script.

**Comment by mirkojovanovic** [comment]
Awesome, thanks a lot! :+1:

**Comment by mirkojovanovic** [comment]
How to disable generic names? For example just "GNU Image Manipulation Program" not that and "Image Editor" for same thing?

**Comment by mirkojovanovic** [comment]
--no-generic option doesn't work.

**Comment by enkore** [comment]
--no-generic is not part of a release yet.

**Comment by mirkojovanovic** [comment]
Ok, thanks. I think you should note that in readme.
