### ISSUE TITLE
Can't get normal binaries to work

### ISSUE THREAD

**Issue by yawanawa** [enkore/j4-dmenu-desktop#52]
So, I used script from readme, and when I run it from terminal everything is fine.
But, after adding a shortcut into xbindkey normal binaries are not executed. I tried to add "term" command but it does nothing.

**Comment by enkore** [comment]
"normal binaries" = console terminals?

=> try the `--term` option with e.g. `xterm`.

**Comment by yawanawa** [comment]
It does not work either xterm and lxterminal.
.xbindkeysrc: `"j4-dmenu-desktop --term="xterm" --dmenu="(cat ; (stest -flx $(echo $PATH | tr : ' ') | sort -u)) | dmenu""
   Super_L`

**Comment by enkore** [comment]
I don't know how xbindkeys parses these strings, but I would expect that the nested double quotes don't work this way.

```
"j4-dmenu-desktop --term=xterm --dmenu='(cat ; (stest -flx $(echo $PATH | tr : \' \') | sort -u)) | dmenu'"
```

Maybe? Not sure. The `\'` might not work.
