### ISSUE TITLE
basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by kovanovic** [enkore/j4-dmenu-desktop#54]
Hi, I have this weird exception  which occurs when string constructor is called with NULL

I call j4-dmenu-desktop like this
`j4-dmenu-desktop --dmenu="dmenu -i -l 10 -sb black -sf red -nb black -nf darkgray -p Run: -fn '-*-terminus-*-*-*-*-14-*-*-*-*-*-*-*'" `

the output when run is:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```

**Comment by enkore** [comment]
#19 #32 #40 

That one should be improved ( #53 )

**Comment by kovanovic** [comment]
Oh, I see, for some reason, my /etc/locale.gen had all of them commented out and no locale was generated. After uncommenting my locale and running locale-gen, it works again :)
