### ISSUE TITLE
Creates Seperate Entries for "Name" and "GenericName"

### ISSUE THREAD

**Issue by CAPTNCAPS** [enkore/j4-dmenu-desktop#64]
A lot of my programs show up twice, because they specify a Name and a GenericName in their .desktop file.
Would be nice if there was an argument to disable this and read just one of the two.

**Comment by KubqoA** [comment]
Is there any update on this issue?

**Comment by Maxr1998** [comment]
Just use the `--no-generic` option, it's available since over three years now: https://github.com/enkore/j4-dmenu-desktop/commit/214e0cdf18d2cfee9634c237c231afe2b5082b2a
