### ISSUE TITLE
option to open at currently active screen instead of the display where the mouse is at

### ISSUE THREAD

**Issue by r79** [enkore/j4-dmenu-desktop#70]
Multi-head user here (Arch, i3), felt like a bug at first until I found out that j4-dmenu always opens at the screen where the cursor is currently placed, instead of the screen which is actually active.

Would be awesome to atleast have an option for this ;)

I was trying to fix it myself and give you a pull request, but I had to find out that C++ isn't that easy to fiddle around with if you never worked with it ._.

**Comment by enkore** [comment]
I don't think dmenu has an option for this.
