### ISSUE TITLE
Launch more than one program at once (workaround/recipe inside)

### ISSUE THREAD

**Issue by enricoT** [enkore/j4-dmenu-desktop#76]
If i type fox in my j4-dmenu-desktop i got firefox just 1 app to run (firefox) if i type thu only one app is available (thunderbird)
It would be nice to make run at the same time 2 or more app, just typing:
fox thu (with one condition: if typing fox thu makes available only 2 app) 
Is that reasonable and wouldnt make the j4-dmenu-desktop faster?

**Comment by meator** [comment]
This would be pretty complicated to implement and I don't think this change would provide much value. I believe that Scriptim's solution solves this problem fairly cleanly.
