### ISSUE TITLE
Compilation fails on FreeBSD 11.2

### ISSUE THREAD

**Issue by 0mp** [enkore/j4-dmenu-desktop#81]
I'm attempting to add j4-dmenu-desktop to the FreeBSD Ports Collection but I get the following error when I try to compile it on FreeBSD 11.2 i386.

Any idea how to fix it?

> ```
> =======================<phase: build          >============================
> ===>  Building for j4-dmenu-desktop-2.16.14
> [1/2] /usr/bin/c++    -O2 -pipe -fstack-protector -fno-strict-aliasing -std=c++11 -Wall -Wextra -pedantic -O2 -O2 -pipe -fstack-protector -fno-strict-aliasing -MD -MT CMakeFiles/j4-dmenu-desktop.dir/src/main.cc.o -MF CMakeFiles/j4-dmenu-desktop.dir/src/main.cc.o.d -o CMakeFiles/j4-dmenu-desktop.dir/src/main.cc.o -c /wrkdirs/usr/ports/x11/j4-dmenu-desktop/work/j4-dmenu-desktop-r2.16-14-g6bb15e8/src/main.cc
> FAILED: CMakeFiles/j4-dmenu-desktop.dir/src/main.cc.o
> /usr/bin/c++    -O2 -pipe -fstack-protector -fno-strict-aliasing -std=c++11 -Wall -Wextra -pedantic -O2 -O2 -pipe -fstack-protector -fno-strict-aliasing -MD -MT CMakeFiles/j4-dmenu-desktop.dir/src/main.cc.o -MF CMakeFiles/j4-dmenu-desktop.dir/src/main.cc.o.d -o CMakeFiles/j4-dmenu-desktop.dir/src/main.cc.o -c /wrkdirs/usr/ports/x11/j4-dmenu-desktop/work/j4-dmenu-desktop-r2.16-14-g6bb15e8/src/main.cc
> In file included from /wrkdirs/usr/ports/x11/j4-dmenu-desktop/work/j4-dmenu-desktop-r2.16-14-g6bb15e8/src/main.cc:2:
> In file included from /wrkdirs/usr/ports/x11/j4-dmenu-desktop/work/j4-dmenu-desktop-r2.16-14-g6bb15e8/src/Main.hh:17:
> /wrkdirs/usr/ports/x11/j4-dmenu-desktop/work/j4-dmenu-desktop-r2.16-14-g6bb15e8/src/Application.hh:111:26: error: use of undeclared identifier 'getline'; did you mean 'std::getline'?
>         while((linelen = getline(linep, linesz, file)) != -1) {
>                          ^~~~~~~
>                          std::getline
> /usr/include/c++/v1/istream:1556:1: note: 'std::getline' declared here
> getline(basic_istream<_CharT, _Traits>& __is,
> ^
> In file included from /wrkdirs/usr/ports/x11/j4-dmenu-desktop/work/j4-dmenu-desktop-r2.16-14-g6bb15e8/src/main.cc:2:
> In file included from /wrkdirs/usr/ports/x11/j4-dmenu-desktop/work/j4-dmenu-desktop-r2.16-14-g6bb15e8/src/Main.hh:17:
> /wrkdirs/usr/ports/x11/j4-dmenu-desktop/work/j4-dmenu-desktop-r2.16-14-g6bb15e8/src/Application.hh:111:26: error: no matching function for call to 'getline'
>         while((linelen = getline(linep, linesz, file)) != -1) {
>                          ^~~~~~~
> /usr/include/c++/v1/istream:1556:1: note: candidate template ignored: could not match 'basic_istream<type-parameter-0-0, type-parameter-0-1>' against 'char **'
> getline(basic_istream<_CharT, _Traits>& __is,
> ^
> In file included from /wrkdirs/usr/ports/x11/j4-dmenu-desktop/work/j4-dmenu-desktop-r2.16-14-g6bb15e8/src/main.cc:2:
> /wrkdirs/usr/ports/x11/j4-dmenu-desktop/work/j4-dmenu-desktop-r2.16-14-g6bb15e8/src/Main.hh:296:75: warning: format specifies type 'unsigned long' but the argument has type 'std::__1::map<std::__1::basic_string<char>, Application *, std::__1::less<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, Application *> > >::size_type' (aka 'unsigned int') [-Wformat]
>         printf("Read %d .desktop files, found %lu apps.\n", parsed_files, apps.size());
>                                               ~~~                         ^~~~~~~~~~~
>                                               %u
> 1 warning and 2 errors generated.
> ninja: build stopped: subcommand failed.
> ===> Compilation failed unexpectedly.
> Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
> the maintainer.
> *** Error code 1
> 
> Stop.
> make: stopped in /usr/ports/x11/j4-dmenu-desktop
> build of x11/j4-dmenu-desktop | j4-dmenu-desktop-2.16.14 ended at Tue Jan 22 11:44:19 CET 2019
> build time: 00:00:06
> !!! build failure encountered !!!
> ```

**Comment by enkore** [comment]
> 
     Many application writers used the name getline before the getline() func-
     tion was introduced in IEEE Std 1003.1 (``POSIX.1''), so a	prototype is
     not provided by default in	order to avoid compatibility problems.	Appli-
     cations that wish to use the getline() function described herein should
     either request a strict IEEE Std 1003.1-2008 (``POSIX.1'')	environment by
     defining the macro	_POSIX_C_SOURCE	to the value 200809 or greater,	or by
     defining the macro	_WITH_GETLINE, prior to	the inclusion of <stdio.h>.
     For compatibility with GNU	libc, defining either _BSD_SOURCE or
     _GNU_SOURCE prior to the inclusion	of <stdio.h> will also make getline()
     available.

FreeBSD's getline(3) -- add "-D_WITH_GETLINE" to the CXXFLAGS.

**Comment by enkore** [comment]
Probably fixed by 13021008

**Comment by 0mp** [comment]
Thank you! I'll give it a spin!

**Comment by 0mp** [comment]
Works just fine. It should be packaged soon.
