### ISSUE TITLE
Specifying `--no-generic` after `--usage-log=` breaks usage log

### ISSUE THREAD

**Issue by Maxr1998** [enkore/j4-dmenu-desktop#82]
Consider the following two commands:
```bash
j4-dmenu-desktop --no-generic --usage-log="$HOME/.cache/dmenu_usage.log"
j4-dmenu-desktop --usage-log="$HOME/.cache/dmenu_usage.log --no-generic"
```

In the first, the dmenu works normally, showing most used apps in the first position, and excluding the generic names from the list.

The second command however shows apps in their alphabetical sorting, completely ignoring the usage log. Generic apps are however excluded.

**Comment by Maxr1998** [comment]
It seems this issue was fixed in 4f98f67a695c75146f1777e3cad9af6e58ec886c, as I could also confirm by rebuilding the package with the change manually added in. However, since there was no release after that commit, the AUR package still includes the bug. Could you please release a new version to make this fix public?

**Comment by enkore** [comment]
I suppose since it's 2019 now I can make another of the annual bugfix + feature releases. Gotta keep the rhythm!

**Comment by enkore** [comment]
Done.
