### ISSUE TITLE
Make shell configurable

### ISSUE THREAD

**Issue by varac** [enkore/j4-dmenu-desktop#86]
Currently, when executing shell scripts my default interactive shell (zsh) is used.
I'd prefer to start them with i.e. dash since it's much faster and scripts don't need all the interactive customisation of my default shell.

**Comment by enkore** [comment]
You can do `SHELL=... j4-d-d ...`

**Comment by varac** [comment]
Great, thx ! Would be good to document this for others as well.

**Comment by enkore** [comment]
Done
