### ISSUE TITLE
Verbose or debug mode

### ISSUE THREAD

**Issue by varac** [enkore/j4-dmenu-desktop#87]
It would be very helpful to run j4-dmenu-desktop in verbose or even debug mode for debugging.

**Comment by enkore** [comment]
That's a compile time flag at this time (`cmake -DCMAKE_BUILD_TYPE=debug`).

**Comment by meator** [comment]
I have implemented logging. There are four loglevels now: `ERROR`, `WARNING`, `INFO` and `DEBUG`. They should provide enough information for debugging and information gathering.

This change isn't released yet, it should appear in the `r3.0` release.
