### ISSUE TITLE
%k support

### ISSUE THREAD

**Issue by jazzpi** [enkore/j4-dmenu-desktop#88]
It seems as though j4 used to have support for `%k`, but it was removed in https://github.com/enkore/j4-dmenu-desktop/commit/579ee11a361fc58bfa43d426fd45a6a7f88be6a7 since it's not used enough.

I noticed this becuase the [Zotero citation manager](https://www.zotero.org/) does use it. The installation process works as follows: Install Zotero to some location (`/opt/zotero` etc.), then symlink the `.desktop` entry to `/usr/local/share/applications`. The desktop entry then contains this line:

    Exec=bash -c "$(dirname $(readlink -f %k))/zotero -url %U"

This seems like a fairly reasonable use case. A quick [GitHub search](https://github.com/search?utf8=%E2%9C%93&q=%25k+extension%3Adesktop&type=Code&ref=advsearch&l=&l=) reveals 637 uses of `%k`.

It seems like the only relevant diff in removing support was a single string concatenation, so supporting it shouldn't have a terrible performance impact, either. Would it be possible to re-add support for `%k`?

**Comment by enkore** [comment]
Fair enough
