### ISSUE TITLE
app fails if LANG=en_DK.utf8 

### ISSUE THREAD

**Issue by goekce** [enkore/j4-dmenu-desktop#93]
Steps to reproduce:
1) uncomment en_DK.utf8 in /etc/locale.gen
2) sudo locale-gen
3) set LANG=en_DK.utf8 in /etc/locale.conf
4) reboot
5) run j4-dmenu-desktop

Behavior:
1)  j4-dmenu-desktop does not accept any keystrokes

If j4-dmenu-desktop is run on the command line, j4-dmenu-desktop throws following warnings:
`
warning: no locale support
warning: no locale modifiers support
`
I am using LANG=en_DK.utf8 to have English as language but not American date and time formatting.

**Comment by enkore** [comment]
That sounds like a dmenu problem, because j4dd doesn't actually handle or display your keyboard input. That's all done by dmenu.

**Comment by goekce** [comment]
I am sorry that I completely forgot about this issue. You are right, it seems to be a dmenu issue.
