### ISSUE TITLE
Unable to start multiple processes with a single instance of j4dd with wait-on

### ISSUE THREAD

**Issue by tmccombs** [enkore/j4-dmenu-desktop#98]
I expected the "wait-on" option to j4dd to start it in a daemon and be able to write to the pipe to start new programs as needed. However, there is a pretty big limitation. After spawning the child process, j4dd waits for it to complete (https://github.com/enkore/j4-dmenu-desktop/blob/475e7804ada2e8152518c292a1be39db1768f5c1/src/Main.hh#L286). This means that if I start a program with j4dd, I can't use write to the pipe to select another program until that first program terminates. This severely diminishes the usefuleness of the wait-on mode.

**Comment by enkore** [comment]
Fixed in master branch
